name: K6 Performance Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  deploy-k6-test-on-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the docker-compose up
        timeout-minutes: 2
        run: docker compose -f docker/docker-compose.yml up -d

      - name: Wait for application
        run: |
          for i in {1..60}; do
            nc -z localhost 8080 && echo success && exit 0
            sleep 2
          done
          echo "Service did not start in time" && exit 1

      - name: Verify Ports
        run: sudo netstat -tulpn | grep LISTEN

      - name: Check running containers
        run: docker ps

      - name: Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: src/scripts/api/test.js
          flags: --out influxdb=http://localhost:8086/k6
        env:
          BASE_URL: "http://localhost:8080"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: k6-report-html
          path: summary.html 

      - name: Build the docker compose down
        timeout-minutes: 2
        run: docker compose down
